"""Generate a PDF audit report from SIOS findings."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sios.pipeline import AuditResult


def _safe(text: str) -> str:
    """Sanitize text for Helvetica (Latin-1 range only)."""
    return (
        text
        .replace("—", "-")   # em dash
        .replace("–", "-")   # en dash
        .replace("'", "'").replace("'", "'")
        .replace("“", '"').replace("”", '"')
        .replace("…", "...")
        .encode("latin-1", errors="replace").decode("latin-1")
    )


def create_report(result: "AuditResult", cpo: str, session_id: str, reports_dir: str = "reports") -> str:
    try:
        from fpdf import FPDF, XPos, YPos
    except ImportError as e:
        raise ImportError("PDF generation requires fpdf2. Run: pip install fpdf2") from e

    Path(reports_dir).mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.add_page()
    W = pdf.epw  # effective page width (~190mm on A4)

    NL = {"new_x": XPos.LMARGIN, "new_y": YPos.NEXT}

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(W, 12, "SIOS AUDIT REPORT", align="C", **NL)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(W, 6, f"Proof (CPO): {cpo[:32]}...", align="C", **NL)
    pdf.cell(W, 6, "Every finding is reproducible and cryptographically verifiable.", align="C", **NL)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Divider ───────────────────────────────────────────────────────────────
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + W, pdf.get_y())
    pdf.ln(6)

    # ── Summary box ───────────────────────────────────────────────────────────
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(W, 10, f"Estimated recoverable: {result.estimated_savings:,.0f} {result.currency}", fill=True, **NL)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(W, 8, f"Findings: {len(result.findings)}", fill=True, **NL)
    pdf.cell(W, 8, f"Transactions analyzed: {result.dataset_rows}", fill=True, **NL)
    pdf.ln(6)

    # ── Findings ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(W, 10, "Findings", **NL)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + W, pdf.get_y())
    pdf.ln(4)

    sorted_findings = sorted(result.findings, key=lambda f: f.estimated_amount or 0, reverse=True)

    for finding in sorted_findings:
        label = finding.type.value.replace("_", " ").title()
        amount_str = f"{finding.estimated_amount:,.0f} {finding.currency}"
        conf_str = f"conf: {finding.confidence:.0%}"

        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(W, 8, _safe(f"[{label}]  {amount_str}  ({conf_str})"), **NL)

        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(W, 6, _safe(finding.title))

        if finding.description:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(W, 6, _safe(finding.description[:220]))
            pdf.set_text_color(0, 0, 0)

        if finding.recommended_actions:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 100, 40)
            for action in finding.recommended_actions[:2]:
                pdf.cell(W, 6, _safe(f"  -> {action}"), **NL)
            pdf.set_text_color(0, 0, 0)

        pdf.ln(4)
        pdf.set_draw_color(230, 230, 230)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + W, pdf.get_y())
        pdf.ln(4)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.multi_cell(
        W, 5,
        _safe(
            "This report was generated by SIOS. "
            "The CPO hash above is a cryptographic fingerprint of the inputs and outputs. "
            "Re-run detection on the same dataset to verify reproducibility. "
            "SIOS - Financial Audit Engine - https://github.com/haynbroit-alt/CPO"
        ),
    )

    out_path = Path(reports_dir) / f"{session_id}.pdf"
    pdf.output(str(out_path))
    return str(out_path)
